---
driver:
  name: docker
platforms:


  - name: debian
    image: debian:latest
    dockerfile: Dockerfile.debian
    build:
      path: .
  - name: ubuntu
    image: ubuntu:latest
    dockerfile: Dockerfile.ubuntu
    build:
      path: .
  - name: oraclelinux
    image: oraclelinux:9
    dockerfile: Dockerfile.oraclelinux
    build:
      path: .     




